name: Deploy PNS-Dhampur School Management System 
 
on: 
  push: 
    branches: [ main ] 

jobs: 
  test: 
    runs-on: ubuntu-latest
    
    services: 
      mysql: 
        image: mysql:8.0 
        env: 
          MYSQL_ROOT_PASSWORD: password 
          MYSQL_DATABASE: pns_dhampur 
        ports: 
          - 3306:3306 
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 

    steps: 
    - uses: actions/checkout@v3 

    - name: Setup PHP 
      uses: shivammathur/setup-php@v2 
      with: 
        php-version: '8.1' 
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql 

    - name: Copy .env 
      run: | 
        cp .env.example .env 
        php -r "file_put_contents('.env', str_replace('DB_DATABASE=laravel', 'DB_DATABASE=pns_dhampur', file_get_contents('.env')));" 
        php -r "file_put_contents('.env', str_replace('DB_USERNAME=root', 'DB_USERNAME=root', file_get_contents('.env')));" 
        php -r "file_put_contents('.env', str_replace('DB_PASSWORD=', 'DB_PASSWORD=password', file_get_contents('.env')));" 

    - name: Install Composer Dependencies 
      run: | 
        composer require doctrine/dbal --dev --no-interaction 
        composer install --no-progress --no-interaction --optimize-autoloader 

    - name: Generate Application Key 
      run: php artisan key:generate 

    - name: Create Database 
      run: | 
        mysql -h 127.0.0.1 -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS pns_dhampur;" 

    - name: Run Migrations 
      run: php artisan migrate --force --verbose 

    - name: Run Tests 
      run: ./vendor/bin/phpunit